name: Deploy React + Vite to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - main # mainブランチにプッシュされたら実行

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # Node.js の設定
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # 使用するNode.jsのバージョン

      # npm依存関係のインストール
      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      # Viteアプリケーションのビルド
      - name: Build Vite
        working-directory: ./frontend
        run: npm run build

      # AWS CLIをセットアップ
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      # ビルドされたファイルをS3にアップロード
      - name: Upload to S3
        run: |
          aws s3 sync ./frontend/dist ${{ secrets.AWS_S3_BACKET_NAME }} --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # CloudFrontキャッシュの無効化
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
