name: Deploy Docker to ECS

on:
  push:
    branches:
      - main # mainブランチにプッシュされたときに実行

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # リポジトリのチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # AWS 認証情報の設定
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      # Dockerログイン
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com

      # Dockerイメージのビルド
      - name: Build Docker image
        working-directory: ./server
        run: |
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com/${{ secrets.AWS_ECR }}:latest -f ./server/Dockerfile ./

      # ECRにDockerイメージをプッシュ
      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com/${{ secrets.AWS_ECR }}:latest

      # ECSタスク定義の更新
    #   - name: Update ECS task definition
    #     run: |
    #       aws ecs update-service --cluster ${{secrets.AWS_CLUSTER_NAME}} --service ${{secrets.AWS_SERVICE_NAME}} --force-new-deployment
